<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250506115452 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE user_device (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, device_id VARCHAR(255) NOT NULL, device_name VARCHAR(255) NOT NULL, device_type VARCHAR(255) NOT NULL, push_token VARCHAR(255) DEFAULT NULL, is_active BOOLEAN NOT NULL, last_active_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6C7DADB3A76ED395 ON user_device (user_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE user_device ADD CONSTRAINT FK_6C7DADB3A76ED395 FOREIGN KEY (user_id) REFERENCES wp_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_version ALTER status TYPE VARCHAR(20)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_version ALTER status DROP DEFAULT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_version ALTER is_major TYPE BOOLEAN
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_version ALTER is_major DROP DEFAULT
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_version ALTER is_major SET NOT NULL
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE user_device DROP CONSTRAINT FK_6C7DADB3A76ED395
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE user_device
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_version ALTER status TYPE VARCHAR(20)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_version ALTER status SET DEFAULT 'draft'
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_version ALTER is_major TYPE BOOLEAN
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_version ALTER is_major SET DEFAULT false
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_version ALTER is_major DROP NOT NULL
        SQL);
    }
}
