<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250504111749 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE document_version (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, version_number VARCHAR(255) NOT NULL, file_path VARCHAR(255) NOT NULL, change_description VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, document_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1B73751FC33F7837 ON document_version (document_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_1B73751FB03A8386 ON document_version (created_by_id)
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_version ADD CONSTRAINT FK_1B73751FC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_version ADD CONSTRAINT FK_1B73751FB03A8386 FOREIGN KEY (created_by_id) REFERENCES wp_users (id) NOT DEFERRABLE INITIALLY IMMEDIATE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE signatory ALTER signed TYPE BOOLEAN
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE signatory ALTER signed SET NOT NULL
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            ALTER TABLE document_version DROP CONSTRAINT FK_1B73751FC33F7837
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE document_version DROP CONSTRAINT FK_1B73751FB03A8386
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE document_version
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE signatory ALTER signed TYPE BOOLEAN
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE signatory ALTER signed DROP NOT NULL
        SQL);
    }
}
